# Generated by Django 5.1 on 2024-09-25 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science Fiction', 'Science Fiction'), ('Biography', 'Biography'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Poetry', 'Poetry')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('categories', models.CharField(blank=True, choices=[('Book', 'Book'), ('Audio', 'Audio'), ('Ebook', 'Ebook'), ('Book & Audio', 'Book & Audio')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('History', 'History'), ('Biography', 'Biography'), ('Fantasy', 'Fantasy'), ('Philosophy', 'Philosophy'), ('Engineering', 'Engineering'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Music', 'Music'), ('Drama', 'Drama'), ('Patriotic', 'Patriotic')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
