# Generated by Django 5.1 on 2024-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('History', 'History'), ('Biography', 'Biography'), ('Fantasy', 'Fantasy'), ('Philosophy', 'Philosophy'), ('Engineering', 'Engineering'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Music', 'Music'), ('Drama', 'Drama'), ('Patriotic', 'Patriotic')], max_length=50, unique=True)),
            ],
        ),
    ]
