# Generated by Django 5.1 on 2024-09-09 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author Name')),
                ('genre', models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science Fiction', 'Science Fiction'), ('Biography', 'Biography'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Poetry', 'Poetry')], max_length=100, null=True, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Book Description')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Date Published')),
                ('rating', models.FloatField(default=0.0, verbose_name='Book Rating')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Trending Status')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Search Query')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Searched At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
