# Generated by Django 5.1 on 2024-09-10 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpbook', '0002_book_previoussearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_trending',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
