# Generated by Django 5.1 on 2024-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpbook', '0004_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(blank=True, choices=[('Book', 'Book'), ('Audio', 'Audio'), ('Ebook', 'Ebook'), ('Book & Audio', 'Book & Audio')], max_length=100, null=True, verbose_name='Media Type'),
        ),
    ]
