# Generated by Django 5.1 on 2024-08-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='reset_token',
        ),
    ]
